name: JuhanActioni

on:
        push:

                
jobs: 
  juhaTestActionJobName:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: github-actions-test@main
        
      - name: Echo test
        run: echo "Test"

