name: JuhanActioni

on:
        push:

                
jobs: 
  juhaTestActionJobName:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Echo test
        run: echo "Test"

