name: JuhanActioni

on:
  push:

                
jobs: 
  juhaTestActionJobName:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Echo test
        run: echo "Test"

  testBranchJob:
    runs-on: ubuntu-20.04

    if: contains(github.ref, "test-branch")
    steps:
      - uses: action/checkout@v2

      - name: Test Branch Job
        run: echo "Running on test-branch!"
